[project]
name = "brown-paper-packages"
version = "0.1.1.20260831"
description = "Brown paper packages (tied up with strings) - Collection of 'a few of my favourite things' -i.e. PyPI packages- in order to stop repeating myself."
readme = "README.md"
license = { file = "LICENSE" }
authors = [ { name = "Dutcho" } ]
requires-python = ">=3.12"
dependencies = [
    "brown-paper-packages[default]",
]
keywords = ["packages", "DRY"]
classifiers = [
  "Development Status :: 1 - Alpha",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/Dutcho/brown-paper-packages"
Repository = "https://github.com/Dutcho/brown-paper-packages"
Documentation = "https://github.com/Dutcho/brown-paper-packages/blob/main/README.md"

[project.optional-dependencies]
utils = [
    "more-itertools",           # iter algorithms
    "sortedcontainers",         # sorted data structures
    "orderedsets",              # order-retaining sets
    "python-dotenv[cli]",       # .env access
    "platformdirs",             # platform dependent paths

    "sortedcontainers-stubs",   # type stubs
]
typing = [
    "typing-extensions",        # new and experimental typing features
    "useful-types",             # reusable protocols
    "annotated-types",          # metadata for Annotated[]
    "annotated-doc",            # Doc for Annotated[], when annotated-types is too much
]
default = [
    "brown-paper-packages[utils,typing]"
]
excel = [
    "openpyxl",                 # process XLSX files, uses defusedxml for safety
    "pyxlsb",                   # process XLSB files
                                # TODO investigate variant pyxlsb2 with more functionality
    "lxml",                     # fast XML parsing, overlap with extra web
    "defusedxml",               # safety from XML bombs, overlap with extra web

    "types-openpyxl",           # type stubs
    "types-lxml",
    "types-defusedxml",
]
data = [
    "polars[pandas,numpy,excel]",
    "duckdb",
	"fsspec",					# for duckdb CSV handling
]
web = [
    "requests",
    "Flask",
    "FastAPI[standard]",
    "BeautifulSoup4",           # uses lxml for speed
    "lxml",                     # fast XML parsing, overlap with extra excel
    "html5lib",
    "defusedxml",               # safety from XML bombs, overlap with extra excel

    "types-requests",           # type stubs
    "types-beautifulsoup4",
    "types-lxml",
    "types-html5lib",
    "types-defusedxml",
]
dev = [
    "mypy",
    "ty",
]
all = [
    "brown-paper-packages[default,excel,data,web,dev]"
]

[build-system]
requires = ["uv_build<1.0"]
build-backend = "uv_build"

[tool.mypy]
strict = true

[tool.ruff]
line-length = 120
